import { Amplify } from 'aws-amplify';

type AmplifyOutputs = Record<string, unknown>;

/**
 * `amplify_outputs.json` is generated by `npx ampx sandbox` (or a deploy
 * pipeline) and is gitignored, so it does not exist in CI or in a fresh
 * checkout. `import.meta.glob` tolerates zero matches, unlike a static
 * import, which lets the app build and run without a deployed backend.
 */
const outputModules = import.meta.glob<{ default: AmplifyOutputs }>('/amplify_outputs.json', {
  eager: true,
});

const outputs = outputModules['/amplify_outputs.json']?.default;

export const isAmplifyConfigured = Boolean(outputs);

/**
 * Configured as a side effect of importing this module, not via an exported
 * function a caller has to remember to invoke. `generateClient()` (see
 * data-client.ts) needs `Amplify.configure()` to have already run, and ES
 * module evaluation order only guarantees that for imports of *this exact
 * file* - so every module that calls `generateClient()` must import this one
 * directly, rather than relying on some other module having configured it
 * first.
 */
if (outputs) {
  Amplify.configure(outputs as Parameters<typeof Amplify.configure>[0]);
}
